#!/bin/bash
# API Change Review Helper - Shows everything needed to review API changes

echo "🔍 NEXUS API CHANGE REVIEW HELPER"
echo "================================="
echo ""
echo "Use this when Claude Code suggests API changes. It shows:"
echo "1. Current API models"
echo "2. Changes to schema files"
echo "3. DeepSeek configuration"
echo "4. How to approve/reject changes"
echo ""

echo "📋 1. CURRENT API MODELS (Snapshot)"
echo "----------------------------------"
python3 scripts/view_api_models.py --simple 2>/dev/null | tail -20

echo ""
echo "📝 2. SCHEMA FILE CHANGES"
echo "------------------------"
./scripts/view_schema_changes_simple.sh 2>/dev/null | grep -A5 "HAS.*CHANGES" || echo "No schema file changes detected."

echo ""
echo "🤖 3. DEEPSEEK CONFIGURATION"
echo "---------------------------"
./scripts/view_deepseek_changes.sh 2>/dev/null | grep -A3 "Current DeepSeek configuration" | tail -5

echo ""
echo "✅ 4. HOW TO REVIEW CHANGES"
echo "--------------------------"
echo "When Claude Code suggests API changes:"
echo ""
echo "STEP 1: View the proposed changes"
echo "   git diff                         # See all changes"
echo "   git diff -- app/models/          # See only model changes"
echo ""
echo "STEP 2: Check what models will be affected"
echo "   python3 scripts/view_api_models.py      # See current models"
echo "   ./scripts/view_schema_changes_simple.sh # See what changed"
echo ""
echo "STEP 3: Look for DeepSeek-related changes"
echo "   ./scripts/view_deepseek_changes.sh      # DeepSeek config"
echo ""
echo "STEP 4: Make a decision"
echo "   ✓ If changes look OK:"
echo "     git add <files>                # Stage changes"
echo "     git commit -m 'Description'    # Commit changes"
echo "   ✗ If changes look wrong:"
echo "     git checkout -- <files>        # Discard changes"
echo "     Tell Claude: 'No, fix XYZ'     # Request corrections"
echo ""
echo "💡 Remember: You're reviewing:"
echo "   - New fields added to models"
echo "   - New models created"
echo "   - Changes to existing fields"
echo "   - DeepSeek API configuration"
echo ""
echo "🔧 Quick commands summary:"
echo "   ./scripts/view_models.sh simple    # Quick model list"
echo "   git status                         # See what files changed"
echo "   git diff --stat                    # Summary of changes"
